### ISSUE TITLE
Doesn't work on Arduino 1.6x

### ISSUE THREAD

**Issue by MP3GMike** [leffhub/DFRobotSIM808_Leonardo_mainboard#1]
The new IDE doesn't allow the folder arch. Is there any workaround?

I tried by copying all into the src folder but then comes a lot of errors in the send SMS example:

In file included from D:\arduino-1.6.5-r5-windows\libraries\SIM808\src/sim808ModemCore.h:5:0,
                 from D:\arduino-1.6.5-r5-windows\libraries\SIM808\src/sim808AccessProvider.h:5,
                 from D:\arduino-1.6.5-r5-windows\libraries\SIM808\src/sim808.h:3,
                 from SendSMS.ino:25:
D:\arduino-1.6.5-r5-windows\libraries\SIM808\src/sim808BaseProvider.h:37:33: error: 'prog_char' has not been declared
   void prepareAuxLocate(PROGMEM prog_char str[], char auxLocate[]);
                                 ^
In file included from D:\arduino-1.6.5-r5-windows\libraries\SIM808\src/sim808AccessProvider.h:5:0,
                 from D:\arduino-1.6.5-r5-windows\libraries\SIM808\src/sim808.h:3,
                 from SendSMS.ino:25:
D:\arduino-1.6.5-r5-windows\libraries\SIM808\src/sim808ModemCore.h:66:35: error: 'prog_char' has not been declared
   virtual size_t writePGM(PROGMEM prog_char str[], bool CR = true);
                                   ^
D:\arduino-1.6.5-r5-windows\libraries\SIM808\src/sim808ModemCore.h:70:34: error: 'prog_char' has not been declared
   void genericCommand_rq(PROGMEM prog_char str[], bool addCR = true);//Generates a generic AT command request from PROGMEM prog_char buffer
                                  ^
Error compiling.

**Comment by leffhub** [comment]
Hi MP3GMike,

Sorry since this project was built before the Arduino IDE1.6 came out, and after this project was finished, Arduino released new IDE 1.6.x with some differences compared with the older version. So for now, the library can only compatible with Arduino IDE 1.5.X. You could get this notice on wiki. http://www.dfrobot.com/wiki/index.php?title=SIM808_with_Leonardo_mainboard_SKU:DFR0355#Drive_SIM808_via_Library
